### ISSUE TITLE
Error's out on centralreport start

### ISSUE THREAD

**Issue by WardsParadox** [CentralReport/CentralReport#105]
```
generic$ centralreport start
Starting CentralReport...
Traceback (most recent call last):
  File "/usr/local/lib/centralreport/centralreport.py", line 19, in <module>
    cr.libs.register_libraries()
  File "/usr/local/lib/centralreport/cr/libs.py", line 21, in register_libraries
    for binary in os.listdir(_binaries_dir):
OSError: [Errno 2] No such file or directory: '/usr/local/lib/centralreport/libs'
```

Would love to get this going. OS X 10.10.2

**Comment by Ninir** [comment]
@WardsParadox We'll have a look at it asap ;)
thanks for reporting!

**Comment by WardsParadox** [comment]
It seems like it's having issues with the dependency. I couldn't figure it out.

**Comment by WardsParadox** [comment]
So I was able to fix the issue (changing the libs to cr in the libs.py file), however the server starts but never seems to actually be accessible.
I also had to install requests and urwid via pip. After that it would start with no error's but will not be accessible at any port config.

**Comment by miniche** [comment]
Hello @WardsParadox 

Sorry for the delay, we are very busy :(
Had you tried to install CentralReport since the sources from the repo?

In fact, and sadly, the documentation is not up to date...

Since the 0.5.0 release, sources do not include Python and Javascript libs anymore.
The package, available using the `curl http://static.centralreport.net/installer | bash` command is fully generated and contains dependencies.

The package is also available here: `http://static.centralreport.net/cr_installer.tar.gz`.

You can follow the curl or the wget "one-line" installer: http://docs.centralreport.net/unix-agent/install

We will update the documentation soon to compile yourself the dependencies.
You need pip and Node.JS to compile front assets.

**Comment by WardsParadox** [comment]
That was able to work. Now to start setting somethings up :smile:

**Comment by WardsParadox** [comment]
Now I'm curious...is it possible to have this running and report back to one central server similar to glances or monit?

**Comment by WardsParadox** [comment]
Is it possible to have them all report back to one "Master" server or is that not a feature?

**Comment by Ninir** [comment]
@WardsParadox Hey, that was one of our feature: the "Central Report online" site.
At the moment, we didn't see such interest in it, so we kind of paused it.

Would you be interested in such stuff? :smiley:

**Comment by WardsParadox** [comment]
In a self hosted environment absolutely; I just do not have a budget for
Cloud solutions right now despite how great they really are. ;-;

Zack McCauley

**Comment by Ninir** [comment]
I guess this can be doable :)
Let us think about a way to do that, and we'll let you know ;)

**Comment by tommydehaas** [comment]
@Ninir i get the same error and your website is unavailable. Can you upload it too github? 

Thanks :smiley:
